### ISSUE TITLE
Issues with indentation

### ISSUE THREAD

**Issue by brettlangdon** [ionutvmi/sublime-jsfmt#37] opened 2015-10-30 14:54 UTC
Over at rdio/jsfmt#179 we have a user which is seeing an issue which might be related to `sublime-jsfmt`.

They are seeing some odd indentation issues, for example:

```js
function test() {
    var mytest;
}

module.exports = function test() {
    var mytest;
}
```

Gets formatted to:

```js
function test() {
    var mytest;
}

module.exports = function test() {
var mytest;
}
```

They are using `node@4.2.1` and this is the `package.json` file from `sublime-text` that they are using:

```json
{
  "name": "sublime-jsfmt",
  "dependencies": {
    "esformatter-braces": "^1.2.1",
    "esformatter-dot-notation": "^1.3.1",
    "esformatter-quotes": "^1.0.3",
    "esformatter-semicolons": "^1.1.1",
    "extend": "^3.0.0",
    "get-stdin": "^4.0.1",
    "jsfmt": "^0.5.0"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "private": true
}
```

I have been unable to reproduce this issue with just `jsfmt`, which leads me to believe it might be related to `sublime-jsfmt`. If anyone has seen this issue before or has any insights into what might be happening, it would be greatly appreciated. (I do not use Sublime, so not sure where to begin).

/cc @damienleroux

**Comment by ionutvmi** [comment] 2015-10-30 20:32
sublime-jsfmt doesn't alter the formatted code in any way.

It looks to me like a configuration issue caused by the jquery preset [here](https://github.com/millermedeiros/esformatter/blob/master/lib/preset/jquery.json#L8). 
I managed to fix the issue using this options:

```
    "options":
    {
        "preset": "jquery",
        "indent":
        {
            "value": "    ",
            "TopLevelFunctionBlock" : 1
        }
    }
```

@damienleroux can you add the configuration above to your sublime-jsfmt.sublime-settings and post here if it fixes the issue ?

related issue: #32

**Comment by damienleroux** [comment] 2015-11-16 13:29
Hi, 

Thank very much you for the solution. Adding "TopLevelFunctionBlock" resolved my problem.

You can close the issue.

**Comment by ionutvmi** [comment] 2015-11-16 14:26
Issue closed.

**Closed by ionutvmi** 2015-11-16 14:26 UTC
